//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentInformationSystemEntities : DbContext
    {
        public StudentInformationSystemEntities()
            : base("name=StudentInformationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCity> tblCity { get; set; }
        public DbSet<tblCollege> tblCollege { get; set; }
        public DbSet<tblDepartment> tblDepartment { get; set; }
        public DbSet<tblException> tblException { get; set; }
        public DbSet<tblRole> tblRole { get; set; }
        public DbSet<tblState> tblState { get; set; }
        public DbSet<tblStudent> tblStudent { get; set; }
        public DbSet<tblStudentHistory> tblStudentHistory { get; set; }
        public DbSet<tblUser> tblUser { get; set; }
    }
}
