//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCollege
    {
        public tblCollege()
        {
            this.tblDepartment = new HashSet<tblDepartment>();
            this.tblStudentHistory = new HashSet<tblStudentHistory>();
        }
    
        public System.Guid CollegeID { get; set; }
        public string CollegeCode { get; set; }
        public string CollegeName { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<tblDepartment> tblDepartment { get; set; }
        public virtual ICollection<tblStudentHistory> tblStudentHistory { get; set; }
    }
}
