//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCity
    {
        public tblCity()
        {
            this.tblStudent = new HashSet<tblStudent>();
        }
    
        public System.Guid CityID { get; set; }
        public string CityName { get; set; }
        public System.Guid StateID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tblState tblState { get; set; }
        public virtual ICollection<tblStudent> tblStudent { get; set; }
    }
}
