//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartment
    {
        public tblDepartment()
        {
            this.tblStudentHistory = new HashSet<tblStudentHistory>();
        }
    
        public System.Guid DepartmentID { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public System.Guid CollegeId { get; set; }
        public int TotalSem { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual tblCollege tblCollege { get; set; }
        public virtual ICollection<tblStudentHistory> tblStudentHistory { get; set; }
    }
}
