//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentHistory
    {
        public System.Guid StudentHistoryID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public System.Guid CollegeID { get; set; }
        public int Semester { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public System.Guid StudentID { get; set; }
    
        public virtual tblCollege tblCollege { get; set; }
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
