//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblState
    {
        public tblState()
        {
            this.tblCity = new HashSet<tblCity>();
        }
    
        public System.Guid StateID { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<tblCity> tblCity { get; set; }
    }
}
